onl: update python3 conversion patch
Drop left over decode()s that are now unneeded since all output is
captured as text=true. Fixes the following error when invoking e.g.
onlpm:

| Traceback (most recent call last):
|   File "/tmp/master/work/accton_as4610-poky-linux-gnueabi/onl/1.1+gitAUTOINC+dd61cc1792_8621a0bab7_4bd372b724-r0/git/tools/make-versions.py", line 112, in <module>
|     o.generate_all()
|   File "/tmp/master/work/accton_as4610-poky-linux-gnueabi/onl/1.1+gitAUTOINC+dd61cc1792_8621a0bab7_4bd372b724-r0/git/tools/make-versions.py", line 43, in generate_all
|     data['build_sha1'] = self.build_sha1.decode('utf8')
| AttributeError: 'str' object has no attribute 'decode'

Also remove some left over out commented code that is not needed
anymore.

Signed-off-by: Jonas Gorski <jonas.gorski@bisdn.de>