onl: fix of_device_id .data assignment
of_device_id::data is a void pointer, so any integers needs to be
explicitly cast to (void *), else gcc complains about it:

| /tmp/tmp.X10jL8zRHJ/optoe.c:236:18: error: initialization of 'const void *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
|   236 | #define ONE_ADDR 1
|       |                  ^
| /tmp/tmp.X10jL8zRHJ/optoe.c:252:43: note: in expansion of macro 'ONE_ADDR'
|   252 |         { .compatible = "optoe1", .data = ONE_ADDR },

Fix this by adding the appropriate casts.

Signed-off-by: Jonas Gorski <jonas.gorski@bisdn.de>