onl: delta-ag5648: fix compilation with 6.6
When updating the modules for 6.6 dni_emc2305 was overlooked as it needs
additional handediting due to its layout.

Fix this up so the driver compiles properly.

Fixes the following build error:

| make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
|   CC [M]  /tmp/tmp.FH1ugIIni4/dni_emc2305.o
| /tmp/tmp.FH1ugIIni4/dni_emc2305.c:95:12: error: 'emc2305_probe_6_3' undeclared here (not in a function); did you mean 'emc2305_probe'?
|    95 |   .probe = emc2305_probe_6_3,
|       |            ^~~~~~~~~~~~~~~~~
|       |            emc2305_probe
| /tmp/tmp.FH1ugIIni4/dni_emc2305.c:383:12: warning: 'emc2305_probe_6_3' defined but not used [-Wunused-function]
|   383 | static int emc2305_probe_6_3(struct i2c_client *client)
|       |            ^~~~~~~~~~~~~~~~~
| make[3]: *** [/home/ubuntu/yocto/master/work-shared/generic-x86-64/kernel-source/scripts/Makefile.build:243: /tmp/tmp.FH1ugIIni4/dni_emc2305.o] Error 1
| make[2]: *** [/home/ubuntu/yocto/master/work-shared/generic-x86-64/kernel-source/Makefile:1913: /tmp/tmp.FH1ugIIni4] Error 2
| make[1]: *** [/home/ubuntu/yocto/master/work-shared/generic-x86-64/kernel-source/Makefile:234: __sub-make] Error 2

Signed-off-by: Jonas Gorski <jonas.gorski@bisdn.de>