kernel: csp7551: update fpga_driver for newer kernels
Add changes from Edgecore's CSP-7551_Driver_Package_20220517.7z to make
the driver build on Linux 5.0.0 and later kernels.

Fixes compile errors:

    /tmp/accton-csp7551/work/accton_csp7551-poky-linux/accton-csp7551-fpga-mod/1.0-r0/fpga_driver.c:772:72: warning: 'enum pci_channel_state' declared inside parameter list will not be visible outside of this definition or declaration
      772 | static pci_ers_result_t fpga_error_detected(struct pci_dev *pdev, enum pci_channel_state error)
          |                                                                        ^~~~~~~~~~~~~~~~~
    /tmp/accton-csp7551/work/accton_csp7551-poky-linux/accton-csp7551-fpga-mod/1.0-r0/fpga_driver.c:772:90: error: parameter 2 ('error') has incomplete type
      772 | static pci_ers_result_t fpga_error_detected(struct pci_dev *pdev, enum pci_channel_state error)
          |                                                                   ~~~~~~~~~~~~~~~~~~~~~~~^~~~~
    /tmp/accton-csp7551/work/accton_csp7551-poky-linux/accton-csp7551-fpga-mod/1.0-r0/fpga_driver.c:772:25: error: function declaration isn't a prototype [-Werror=strict-prototypes]
      772 | static pci_ers_result_t fpga_error_detected(struct pci_dev *pdev, enum pci_channel_state error)
          |                         ^~~~~~~~~~~~~~~~~~~
    /tmp/accton-csp7551/work/accton_csp7551-poky-linux/accton-csp7551-fpga-mod/1.0-r0/fpga_driver.c: In function 'fpga_ioctl':
    /tmp/accton-csp7551/work/accton_csp7551-poky-linux/accton-csp7551-fpga-mod/1.0-r0/fpga_driver.c:923:62: error: macro "access_ok" passed 3 arguments, but takes just 2
      923 |         if (!access_ok(VERIFY_READ, user_addr, _IOC_SIZE(cmd)))
          |                                                              ^

    Signed-off-by: Roger Luethi <roger.luethi@bisdn.de>

diff --git a/conf/machine/accton-csp7551.conf b/conf/machine/accton-csp7551.conf
index fb98d625..1f39b667 100644
--- a/conf/machine/accton-csp7551.conf
+++ b/conf/machine/accton-csp7551.conf
@@ -32,7 +32,6 @@ ONIE_MACHINE_TYPE = "csp7551"

 MACHINE_EXTRA_RDEPENDS += " \
     accton-csp7551-cpld-mod \
-    accton-csp7551-fpga-mod \
 "

 MACHINE_EXTRA_RDEPENDS += "platform-${ONIE_MACHINE_TYPE}"

Signed-off-by: Roger Luethi <roger.luethi@bisdn.de>