accton-csp7551.conf: disable accton-csp7551-fpga-mod
access_ok had 2 arguments since Linux v5.0
(commmit 96d4f267e40f9509e8a66e2b39e8b95655617693)

enum pci_channel_state removed in
commit 16d79cd4e23b1964d36c041ab027505ceacbbeeb

/tmp/accton-csp7551/work/accton_csp7551-poky-linux/accton-csp7551-fpga-mod/1.0-r0/fpga_driver.c:772:72: warning: 'enum pci_channel_state' declared inside parameter list will not be visible outside of this definition or declaration
  772 | static pci_ers_result_t fpga_error_detected(struct pci_dev *pdev, enum pci_channel_state error)
      |                                                                        ^~~~~~~~~~~~~~~~~
/tmp/accton-csp7551/work/accton_csp7551-poky-linux/accton-csp7551-fpga-mod/1.0-r0/fpga_driver.c:772:90: error: parameter 2 ('error') has incomplete type
  772 | static pci_ers_result_t fpga_error_detected(struct pci_dev *pdev, enum pci_channel_state error)
      |                                                                   ~~~~~~~~~~~~~~~~~~~~~~~^~~~~
/tmp/accton-csp7551/work/accton_csp7551-poky-linux/accton-csp7551-fpga-mod/1.0-r0/fpga_driver.c:772:25: error: function declaration isn't a prototype [-Werror=strict-prototypes]
  772 | static pci_ers_result_t fpga_error_detected(struct pci_dev *pdev, enum pci_channel_state error)
      |                         ^~~~~~~~~~~~~~~~~~~
/tmp/accton-csp7551/work/accton_csp7551-poky-linux/accton-csp7551-fpga-mod/1.0-r0/fpga_driver.c: In function 'fpga_ioctl':
/tmp/accton-csp7551/work/accton_csp7551-poky-linux/accton-csp7551-fpga-mod/1.0-r0/fpga_driver.c:923:62: error: macro "access_ok" passed 3 arguments, but takes just 2
  923 |         if (!access_ok(VERIFY_READ, user_addr, _IOC_SIZE(cmd)))
      |                                                              ^

Signed-off-by: Roger Luethi <roger.luethi@bisdn.de>