kernel: intel-bf-kdrv: fix build error for Linux >= 5.15
Fixes build error caused by Linux 5.15 mainline change
67961e77a39b ("PCI/MSI: Rename msi_desc::masked").

  CC [M]  /opt/bf-sde-9.9.0/packages/bf-drivers-9.9.0/kdrv/bf_kdrv/bf_kdrv.o
/opt/bf-sde-9.9.0/packages/bf-drivers-9.9.0/kdrv/bf_kdrv/bf_kdrv.c: In function 'bf_msix_mask_irq':
/opt/bf-sde-9.9.0/packages/bf-drivers-9.9.0/kdrv/bf_kdrv/bf_kdrv.c:190:23: error: 'struct msi_desc' has no member named 'masked'
  190 |   u32 mask_bits = desc->masked;
      |                       ^~
/opt/bf-sde-9.9.0/packages/bf-drivers-9.9.0/kdrv/bf_kdrv/bf_kdrv.c:200:24: error: 'struct msi_desc' has no member named 'masked'
  200 |   if (mask_bits != desc->masked) {
      |                        ^~
/opt/bf-sde-9.9.0/packages/bf-drivers-9.9.0/kdrv/bf_kdrv/bf_kdrv.c:203:9: error: 'struct msi_desc' has no member named 'masked'
  203 |     desc->masked = mask_bits;
      |         ^~

Signed-off-by: Roger Luethi <roger.luethi@bisdn.de>