onl: fix build with PyYAML 6.0
yaml.load without loader is deprecated and unsafe [1], and was removed
with PyYAML 6.0, which kirkstone ships.

The default loader used by yaml.load was the FullLoader, so replace all
instances of yaml.load with the shortcut function yaml.full_load.

[1] https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation

Fixes the following error on build for x86:

| DEBUG: Executing shell function do_configure
| Traceback (most recent call last):
|   File "/tmp/kirkstone/work/accton_as5835_54x-poky-linux/onl/1.1+gitAUTOINC+dd61cc1792_8621a0bab7_4bd372b724-r0/git/sm/infra/builder/unix/tools/modtool.py", line 21, in __load_module
|     d = yaml.load(open(fname))
| TypeError: load() missing 1 required positional argument: 'Loader'
|
| During handling of the above exception, another exception occurred:
|
| Traceback (most recent call last):
|   File "/tmp/kirkstone/work/accton_as5835_54x-poky-linux/onl/1.1+gitAUTOINC+dd61cc1792_8621a0bab7_4bd372b724-r0/git/sm/infra/builder/unix/tools/modtool.py", line 123, in <module>
|     mm.load_modules(ops.dbroot)
|   File "/tmp/kirkstone/work/accton_as5835_54x-poky-linux/onl/1.1+gitAUTOINC+dd61cc1792_8621a0bab7_4bd372b724-r0/git/sm/infra/builder/unix/tools/modtool.py", line 43, in load_modules
|     self.__load_module(os.path.join(root, f))
|   File "/tmp/kirkstone/work/accton_as5835_54x-poky-linux/onl/1.1+gitAUTOINC+dd61cc1792_8621a0bab7_4bd372b724-r0/git/sm/infra/builder/unix/tools/modtool.py", line 23, in __load_module
|     self.logger.exception()
| TypeError: Logger.exception() missing 1 required positional argument: 'msg'
| WARNING: exit code 1 from a shell command.

Signed-off-by: Jonas Gorski <jonas.gorski@bisdn.de>